## Read the AK (actinic keratosis) data sets in both of their source formats
## (SAS "ak.sas7bdat" and SPSS "ak.sav"), check whether they contain the same
## data, and write a Markdown report describing the data set to
## "ak_data_description.md".
##
## NOTE ON READ ORDER: on this machine, reading ak.sav with haven::read_sav()
## *before* haven::read_sas() crashes the R session (a segfault in the
## underlying ReadStat library). Reading the SAS file first avoids this, so
## keep read_sas() ahead of read_sav() below.

library(haven)

sas_path <- "ak.sas7bdat"
sav_path <- "ak.sav"

sas <- read_sas(sas_path)
sav <- read_sav(sav_path)

## ---- Compare the two data sets -------------------------------------------

strip_attrs <- function(x) {
  attributes(x)[c("label", "format.spss", "format.sas", "display_width")] <- NULL
  x
}

same_dim   <- identical(dim(sas), dim(sav))
same_names <- identical(names(sas), names(sav))

value_diffs <- character(0)
if (same_names) {
  for (col in names(sas)) {
    a <- strip_attrs(sas[[col]])
    b <- strip_attrs(sav[[col]])
    if (!isTRUE(all.equal(as.vector(a), as.vector(b)))) {
      value_diffs <- c(value_diffs, col)
    }
  }
}

identical_values <- same_dim && same_names && length(value_diffs) == 0

## Metadata (variable labels, display formats) is allowed to differ between
## the two file formats -- only the data values themselves are compared above.
label_diffs <- character(0)
if (same_names) {
  for (col in names(sas)) {
    lab_sas <- attr(sas[[col]], "label")
    lab_sav <- attr(sav[[col]], "label")
    if (!identical(lab_sas, lab_sav)) label_diffs <- c(label_diffs, col)
  }
}

cat("Dimensions match:      ", same_dim, "\n")
cat("Variable names match:  ", same_names, "\n")
cat("Data values identical: ", identical_values, "\n")
if (length(value_diffs) > 0) cat("Columns with differing values:", paste(value_diffs, collapse = ", "), "\n")
if (length(label_diffs) > 0) cat("Columns with differing labels: ", paste(label_diffs, collapse = ", "), "\n")

## ---- Build a per-variable summary (based on the SAS version) ------------

describe_var <- function(x, name) {
  label <- attr(x, "label")
  if (is.null(label)) label <- ""
  n <- length(x)
  n_missing <- sum(is.na(x))
  if (is.character(x)) {
    type <- "character"
    stats <- sprintf("%d unique values", length(unique(x)))
  } else {
    type <- "numeric"
    stats <- sprintf(
      "min = %s, max = %s, mean = %s, sd = %s",
      format(min(x, na.rm = TRUE)),
      format(max(x, na.rm = TRUE)),
      format(round(mean(x, na.rm = TRUE), 2)),
      format(round(sd(x, na.rm = TRUE), 2))
    )
  }
  data.frame(
    Variable = name,
    Label = label,
    Type = type,
    Missing = n_missing,
    Summary = stats,
    stringsAsFactors = FALSE
  )
}

var_table <- do.call(rbind, lapply(names(sas), function(nm) describe_var(sas[[nm]], nm)))

## ---- Write the Markdown report -------------------------------------------

md <- c(
  "# AK data set description",
  "",
  sprintf("Generated by `compare_ak_data.R` on %s.", format(Sys.time(), "%Y-%m-%d %H:%M")),
  "",
  "## Source files",
  "",
  sprintf("- `%s` (SAS transport format)", sas_path),
  sprintf("- `%s` (SPSS format)", sav_path),
  "",
  "Both files were read with the [haven](https://haven.tidyverse.org/) package.",
  "",
  "## Are the two files identical?",
  "",
  sprintf("- Dimensions match: **%s** (%d rows x %d columns)", same_dim, nrow(sas), ncol(sas)),
  sprintf("- Variable names match: **%s**", same_names),
  sprintf("- Data values identical: **%s**", identical_values),
  if (length(value_diffs) > 0)
    sprintf("- Columns with differing values: %s", paste(value_diffs, collapse = ", "))
  else
    "- No differences found in any data values.",
  if (length(label_diffs) > 0)
    sprintf("- Variable labels differ (metadata only, values unaffected) for: %s", paste(label_diffs, collapse = ", "))
  else
    NULL,
  "",
  "## Variables",
  "",
  "| Variable | Label | Type | Missing | Summary |",
  "|---|---|---|---|---|",
  apply(var_table, 1, function(r) sprintf("| %s | %s | %s | %s | %s |", r["Variable"], r["Label"], r["Type"], r["Missing"], r["Summary"])),
  "",
  "## Notes",
  "",
  "- `ID`: subject identifier (character, e.g. \"A 1\").",
  "- `woman`: sex indicator (1 = woman, 0 = man).",
  "- `Alder`: age in years (\"Alder\" is Danish for age).",
  "- `Q1`-`Q10`: the 10 AKQoL questionnaire item responses.",
  "- `score9`, `score10`: summary scores (sum of 9 and 10 of the items, respectively).",
  ""
)

writeLines(md, "ak_data_description.md")
cat("\nReport written to ak_data_description.md\n")
