## Generate an overview of the functions exported by the "twigg" package
## (installed from github::SebastianKvist99/twigg) and write it to
## twigg_function_overview.md.

library(tools)

pkg <- "twigg"
library(pkg, character.only = TRUE)
db <- Rd_db(pkg)
names(db) <- sub("\\.Rd$", "", names(db))

exported <- sort(ls(paste0("package:", pkg)))
is_fun <- vapply(exported, function(nm) is.function(get(nm, envir = asNamespace(pkg))), logical(1))
funs <- exported[is_fun]
data_objs <- exported[!is_fun]

get_section <- function(rd, tag) {
  x <- tools:::RdTags(rd)
  idx <- which(x == tag)
  if (length(idx) == 0) return("")
  txt <- capture.output(Rd2txt(rd[[idx[1]]], fragment = TRUE, options = list(underline_titles = FALSE)))
  paste(trimws(txt[nzchar(trimws(txt))]), collapse = " ")
}

get_usage <- function(rd) {
  x <- tools:::RdTags(rd)
  idx <- which(x == "\\usage")
  if (length(idx) == 0) return("")
  txt <- capture.output(Rd2txt(rd[[idx[1]]], fragment = TRUE, options = list(underline_titles = FALSE)))
  txt <- txt[cumsum(nzchar(txt)) > 0]
  paste(txt, collapse = "\n")
}

desc <- read.dcf(system.file("DESCRIPTION", package = pkg))

md <- c(
  "# twigg: function overview",
  "",
  sprintf("Package: **%s** (version %s)", desc[1, "Package"], desc[1, "Version"]),
  "",
  desc[1, "Description"],
  "",
  sprintf("- Source: %s", desc[1, "URL"]),
  sprintf("- Maintainer: %s", desc[1, "Maintainer"]),
  "",
  sprintf("Generated by `twigg_function_overview.R` on %s.", format(Sys.time(), "%Y-%m-%d %H:%M")),
  "",
  "## Exported functions",
  "",
  sprintf("The package exports %d functions and %d example data sets.", length(funs), length(data_objs)),
  ""
)

for (nm in funs) {
  rd <- db[[nm]]
  if (is.null(rd)) {
    md <- c(md, sprintf("### `%s`", nm), "", "*(no documentation found)*", "")
    next
  }
  title <- get_section(rd, "\\title")
  description <- get_section(rd, "\\description")
  usage <- get_usage(rd)
  md <- c(
    md,
    sprintf("### `%s`", nm),
    "",
    sprintf("**%s**", title),
    "",
    description,
    "",
    "```r",
    usage,
    "```",
    ""
  )
}

md <- c(md, "## Example data sets", "")
for (nm in data_objs) {
  rd <- db[[nm]]
  title <- if (!is.null(rd)) get_section(rd, "\\title") else ""
  description <- if (!is.null(rd)) get_section(rd, "\\description") else ""
  md <- c(md, sprintf("- **`%s`** -- %s. %s", nm, title, description))
}
md <- c(md, "")

writeLines(md, "twigg_function_overview.md")
cat("Wrote twigg_function_overview.md describing", length(funs), "functions and", length(data_objs), "data sets\n")
